Ft es6modules
DjibrilM/Awesome-books pull request #5
Opened 2023-06-12 11:08 UTC by DjibrilM

## In the following pull request I introduced 

- ES6 modules 
-  ES6 syntaxes and time outputting

2023-06-12 11:15 UTC, prolajumokeoni commented
Hi @DjibrilM, Kindly fix stylelint errors and add the future feature section to your readme 👍🏿

2023-06-12 16:54 UTC, Owusu-Desmond requested changes
Hi @DjibrilM , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please make sure your app works are expected, currently, I can't add a book and the current date and time is not displaying.
  [Screencast from 06-12-2023 04:53:12 PM.webm](https://github.com/DjibrilM/Awesome-books/assets/92303891/a22d9c38-edc8-4a83-a8e8-ea81e1b0a28c)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-12 16:54 UTC, Owusu-Desmond commented on main.js
>    }
- [ ] Please from the project requirement, you should create the entry point for your JavaScript code called `index.js` :blush: 

- [ ] From the project requirement, you should divide your code into reasonable modules. I think can create a module for this `Main` class in your main.js and import the module into the `main.js` which is supposed to be `index.js` as your app entry point. :relaxed:

2023-06-13 15:26 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @DjibrilM and @AsumVictor 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 15:26 UTC, tresorsawasawa commented on index.js
>      document.querySelector('.active').classList.remove('active');
- [ ] As mentioned by the previous reviewer and for the project requirements, please make sure your app is working as expected, currently, User can't `add a book` (and impossible to test the `remove` action as there is no added book), the` current date and time is not displaying`, and the `contact page doesn't work`. Make sure you fix those issues to match the expected result.
I recommend you first test all the features of your application and make sure everything is working before requesting a new review.

2023-06-13 16:15 UTC, DjibrilM commented
https://github.com/DjibrilM/Awesome-books/assets/82331014/e9dd24c7-4883-4486-a80a-5622c122d2cd

2023-06-13 16:45 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @DjibrilM ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed GitHub Flow ✔️
- Linters are passing ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 17:01 UTC, merged